'use strict';
const BRANDS=["Bosch","Bremen","Gedore","Lotus","Lynus","Makita","Motomil"],CATS=["Acessórios e consumíveis","Bombas e hidráulica","Compressores e pneumática","Corte e desbaste","Elevação e movimentação","Ferramentas e acessórios","Ferramentas manuais","Furadeiras e perfuração","Geradores e energia","Jardinagem e campo","Medição","Soldagem"],P=(window.TT_ROWS||'').split('\n').filter(Boolean).map(r=>{let x=r.split('|');return {sku:x[0],name:x[1],ref:x[2],brand:BRANDS[+x[3]],cat:CATS[+x[4]],large:x[5]==='1'}}),E=document.getElementById('app'),$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]+/g,' ').trim(),S=[['Henrique','5573981029474'],['Sergio','5573982571530'],['Marcos','5573981300146']];
let cart=JSON.parse(localStorage.tt_cart||'[]'),page=1,chat={options:[],pending:null,list:null,more:false,name:false,seller:null};
function save(){localStorage.tt_cart=JSON.stringify(cart);$('#quoteCount').textContent=cart.reduce((a,x)=>a+x.q,0);drawer()}
function findSku(s){return P.find(p=>p.sku===String(s))}function add(p,q=1){let x=cart.find(i=>i.s===p.sku);x?x.q+=q:cart.push({s:p.sku,q});save();toast('Produto adicionado ao orçamento.')}
function toast(t){let x=$('.toast');if(!x){x=document.createElement('div');x.className='toast';x.style='position:fixed;left:50%;bottom:90px;transform:translateX(-50%);background:#111;color:#fff;padding:12px 16px;border-radius:12px;z-index:300;font-weight:800';document.body.append(x)}x.textContent=t;clearTimeout(x.t);x.t=setTimeout(()=>x.remove(),2200)}
function seller(sticky=false){if(sticky&&chat.seller)return chat.seller;let i=+(localStorage.tt_seller||0),s=S[i%3];localStorage.tt_seller=i+1;if(sticky)chat.seller=s;return s}
function msgText(name='Cliente'){return `Olá. Sou ${name}. Vim pelo site da TEM TUDO e quero atendimento para:\n\n`+cart.map((x,i)=>{let p=findSku(x.s);return `${i+1}. ${x.q}x ${p.name} | SKU ${p.sku}${p.ref?' | Ref. '+p.ref:''}`}).join('\n')+'\n\nFavor confirmar disponibilidade e valores.'}
function wa(s,t=''){return `https://wa.me/${s[1]}${t?'?text='+encodeURIComponent(t):''}`}function openWa(){let s=seller();open(wa(s,`Olá, ${s[0]}. Vim pelo site da TEM TUDO e gostaria de atendimento.`),'_blank')}
function score(p,q){q=norm(q);let h=norm([p.name,p.sku,p.ref,p.brand,p.cat].join(' ')),n=0;if(norm(p.sku)===q)n+=100;if(p.ref&&norm(p.ref)===q)n+=90;if(h.includes(q))n+=30;q.split(' ').forEach(w=>{if(w&&h.includes(w))n+=w.length>4?6:2});return n}function search(q,n=9999){if(!norm(q))return P.slice(0,n);return P.map(p=>[p,score(p,q)]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]).slice(0,n).map(x=>x[0])}
function icon(p){return p.cat.includes('Bombas')?'💧':p.cat.includes('Geradores')?'⚡':p.cat.includes('Soldagem')?'🔥':p.cat.includes('Jardinagem')?'🌿':p.cat.includes('Medição')?'📏':'🔧'}
function card(p){return `<article class="card"><div class="product-visual"><span class="badge">${p.brand}</span>${p.large?'<span class="badge large-badge">Grande porte</span>':''}<span class="emoji">${icon(p)}</span></div><div class="card-body"><h3>${esc(p.name)}</h3><div class="meta">SKU: ${p.sku}<br>Ref.: ${esc(p.ref||'Não informada')}<br>${esc(p.cat)}</div><div class="availability">Consultar disponibilidade</div></div><div class="card-actions"><button class="btn btn-outline" data-view="${p.sku}">Detalhes</button><button class="btn btn-primary" data-add="${p.sku}">Adicionar</button></div></article>`}
function head(t,k,sub=''){return `<section class="page-head"><div class="wrap"><div class="eyebrow">${k}</div><h1 class="title">${t}</h1><p class="copy">${sub}</p></div></section>`}function route(){return (location.hash||'#/inicio').slice(1).split('?')[0]}
function home(){let f=P.filter(x=>x.large).slice(0,8);return `<section class="hero"><div class="wrap hero-in"><div><div class="eyebrow">Ferramentas para quem faz acontecer</div><h1 class="display">Máquinas, ferramentas e <span>soluções profissionais.</span></h1><p class="lead">Busca manual, catálogo completo, orçamento digital e atendimento consultivo em Eunápolis.</p><div class="hero-actions"><a class="btn btn-primary" href="#/catalogo">Explorar catálogo</a><button class="btn btn-dark" data-chat>Abrir assistente</button></div></div><div class="hero-visual"><img class="hero-mascot" data-asset="1"></div></div></section><div class="wrap"><div class="stats"><div class="stat"><strong>${P.length}</strong><span>produtos cadastrados</span></div><div class="stat"><strong>7</strong><span>marcas profissionais</span></div><div class="stat"><strong>WhatsApp</strong><span>rotação de vendedores</span></div><div class="stat"><strong>Eunápolis</strong><span>atendimento local</span></div></div></div><section class="section"><div class="wrap"><div class="eyebrow">Destaques de grande porte</div><h2 class="title">Equipamentos em destaque</h2><div class="grid">${f.map(card).join('')}</div></div></section>`}
