const seedProducts=[
{sku:'4838',name:'Cavalete Automotivo 6 Toneladas',brand:'Bremen',category:'Automotivo',application:'sustentação de veículos oficina mecânica',tags:['6 ton','mecânica']},
{sku:'9287',name:'Cavalete Automotivo 2 Toneladas',brand:'Bremen',category:'Automotivo',application:'sustentação de veículos leves',tags:['2 ton','mecânica']},
{sku:'STR-6012',name:'Bomba Manual para Óleo 12 L',brand:'Bremen',category:'Lubrificação',application:'transferência de óleo manutenção',tags:['12 L','óleo']},
{sku:'6433',name:'Bomba Manual para Graxa 8 kg',brand:'Bremen',category:'Lubrificação',application:'engraxar máquinas veículos',tags:['8 kg','graxa']},
{sku:'3416',name:'Chave de Impacto Pneumática',brand:'Bremen',category:'Pneumática',application:'soltar apertar porcas oficina',tags:['impacto','ar comprimido']},
{sku:'GBH-2-24',name:'Martelete Perfurador 820 W',brand:'Bosch',category:'Ferramentas Elétricas',application:'furar concreto alvenaria demolição leve',tags:['820 W','concreto']},
{sku:'GSB-13-RE',name:'Furadeira de Impacto 650 W',brand:'Bosch',category:'Ferramentas Elétricas',application:'furar madeira metal alvenaria',tags:['650 W','impacto']},
{sku:'GWS-700',name:'Esmerilhadeira Angular 4 1/2 pol',brand:'Bosch',category:'Ferramentas Elétricas',application:'corte desbaste metal',tags:['4 1/2','metal']},
{sku:'DCD776',name:'Parafusadeira e Furadeira de Impacto 20 V',brand:'DeWalt',category:'Ferramentas a Bateria',application:'parafusar furar madeira metal alvenaria',tags:['20 V','bateria']},
{sku:'DW-801',name:'Esmerilhadeira Angular 850 W',brand:'DeWalt',category:'Ferramentas Elétricas',application:'cortar desbastar metal',tags:['850 W','metal']},
{sku:'GED-19',name:'Jogo de Chaves Combinadas 6 a 22 mm',brand:'Gedore',category:'Ferramentas Manuais',application:'aperto manutenção mecânica',tags:['chaves','mecânica']},
{sku:'GED-ALIC',name:'Alicate Universal 8 pol',brand:'Gedore',category:'Ferramentas Manuais',application:'corte aperto elétrica manutenção',tags:['8 pol','alicate']},
{sku:'LOT-500',name:'Lavadora de Alta Pressão 1500 W',brand:'Lotus',category:'Limpeza',application:'lavar pisos veículos fachadas',tags:['1500 W','lavagem']},
{sku:'LOT-COMP',name:'Compressor de Ar 24 L',brand:'Lotus',category:'Compressores',application:'pintura calibragem ferramentas pneumáticas',tags:['24 L','ar']},
{sku:'LYN-MOT',name:'Motor Elétrico Monofásico 2 CV',brand:'Lynus',category:'Motores',application:'máquinas bombas equipamentos',tags:['2 CV','monofásico']},
{sku:'LYN-SOLDA',name:'Máquina de Solda Inversora 160 A',brand:'Lynus',category:'Solda',application:'soldagem eletrodo manutenção serralheria',tags:['160 A','inversora']},
{sku:'VON-CHAVE',name:'Jogo de Soquetes 1/2 pol 22 peças',brand:'Vonder',category:'Ferramentas Manuais',application:'manutenção automotiva aperto',tags:['22 peças','soquetes']},
{sku:'VON-BOMBA',name:'Bomba Periférica 1/2 CV',brand:'Vonder',category:'Bombas',application:'transferência de água residência jardim',tags:['1/2 CV','água']}
];

const state={products:[],quote:{},brand:'Todas',search:'',files:0,misses:0,messages:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const normalize=s=>(s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const escapeHtml=s=>(s||'').toString().replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function load(){
 try{state.products=JSON.parse(localStorage.getItem('tt_products'))||seedProducts}catch{state.products=seedProducts}
 try{state.quote=JSON.parse(localStorage.getItem('tt_quote'))||{}}catch{state.quote={}}
 try{state.files=Number(localStorage.getItem('tt_files')||0)}catch{}
 route();renderBrands();renderCatalog();renderQuote();newConversation(false);updateMetrics();
}
function save(){localStorage.setItem('tt_products',JSON.stringify(state.products));localStorage.setItem('tt_quote',JSON.stringify(state.quote));localStorage.setItem('tt_files',state.files)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function route(){const id=(location.hash||'#inicio').slice(1);$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$('#mainNav')?.classList.remove('open');window.scrollTo({top:0,behavior:'instant'});if(id==='catalogo')renderCatalog();if(id==='orcamento')renderQuote();if(id==='admin')updateMetrics()}
window.addEventListener('hashchange',route);
$$('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);
$('#menuBtn').onclick=()=>$('#mainNav').classList.toggle('open');

function renderBrands(){const brands=['Todas',...new Set(state.products.map(p=>p.brand).filter(Boolean))];$('#brandFilters').innerHTML=brands.map(b=>`<button class="${state.brand===b?'active':''}" data-brand="${escapeHtml(b)}">${escapeHtml(b)}</button>`).join('');$$('[data-brand]').forEach(b=>b.onclick=()=>{state.brand=b.dataset.brand;renderBrands();renderCatalog()})}
function filtered(){const q=normalize(state.search);return state.products.filter(p=>{const brand=state.brand==='Todas'||p.brand===state.brand;const hay=normalize([p.sku,p.name,p.brand,p.category,p.application,(p.tags||[]).join(' ')].join(' '));return brand&&(!q||q.split(' ').every(w=>hay.includes(w)))})}
function renderCatalog(){const items=filtered();$('#catalogStats').textContent=`${items.length} produto(s) exibido(s) de ${state.products.length}`;$('#productGrid').innerHTML=items.length?items.map(productCard).join(''):'<div class="empty-state">Nenhum produto encontrado. Tente outro nome, marca, referência ou serviço.</div>';$$('[data-add]').forEach(b=>b.onclick=()=>addQuote(b.dataset.add));$$('[data-ask]').forEach(b=>b.onclick=()=>{const p=findProduct(b.dataset.ask);location.hash='assistente';setTimeout(()=>sendUser(`Quero saber mais sobre ${p.name} (${p.sku})`),100)})}
function productCard(p){return `<article class="product-card"><div class="product-visual">${escapeHtml((p.brand||'TT').slice(0,2).toUpperCase())}</div><small>${escapeHtml(p.brand)} · ${escapeHtml(p.sku)}</small><h3>${escapeHtml(p.name)}</h3><div class="product-tags">${[p.category,...(p.tags||[])].filter(Boolean).slice(0,3).map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><footer><button class="btn secondary" data-ask="${escapeHtml(p.sku)}">Detalhes</button><button class="btn primary" data-add="${escapeHtml(p.sku)}">Adicionar</button></footer></article>`}
$('#catalogSearch').oninput=e=>{state.search=e.target.value;renderCatalog()};$('#clearSearch').onclick=()=>{$('#catalogSearch').value='';state.search='';renderCatalog()};
function findProduct(sku){return state.products.find(p=>p.sku===sku)}
function addQuote(sku,qty=1){const p=findProduct(sku);if(!p)return;state.quote[sku]=(state.quote[sku]||0)+Number(qty||1);save();renderQuote();toast(`${p.name} adicionado`)}
function changeQty(sku,delta){state.quote[sku]=Math.max(0,(state.quote[sku]||0)+delta);if(!state.quote[sku])delete state.quote[sku];save();renderQuote()}
function quoteEntries(){return Object.entries(state.quote).map(([sku,qty])=>({product:findProduct(sku),qty})).filter(x=>x.product)}
function renderQuote(){const entries=quoteEntries();const html=entries.length?entries.map(({product:p,qty})=>`<article class="quote-item"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.brand)} · ${escapeHtml(p.sku)}</small></div><div class="qty-control"><button data-dec="${p.sku}">−</button><span>${qty}</span><button data-inc="${p.sku}">+</button></div><button class="remove-btn" data-remove="${p.sku}" aria-label="Remover">×</button></article>`).join(''):'<div class="empty-state">Seu orçamento está vazio. Adicione produtos pelo catálogo ou pelo assistente.</div>';$('#quoteItems').innerHTML=html;$('#drawerItems').innerHTML=entries.length?entries.map(({product:p,qty})=>`<div class="drawer-product"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.sku)}</small></div><b>${qty}x</b></div>`).join(''):'<div class="empty-state">Nenhum item.</div>';const total=entries.reduce((s,x)=>s+x.qty,0);$('#quoteCount').textContent=total;$('#summaryTypes').textContent=entries.length;$('#summaryQty').textContent=total;$('#drawerSubtitle').textContent=`${total} item(ns)`;$$('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));$$('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));$$('[data-remove]').forEach(b=>b.onclick=()=>{delete state.quote[b.dataset.remove];save();renderQuote()});updateMetrics()}
$('#clearQuote').onclick=()=>{if(confirm('Limpar todo o orçamento?')){state.quote={};save();renderQuote()}};
function quoteText(){const lines=quoteEntries().map(({product:p,qty})=>`${qty}x — ${p.name} | ${p.brand} | Ref. ${p.sku}`);const name=$('#customerName').value.trim();const notes=$('#quoteNotes').value.trim();return [`ORÇAMENTO TEM TUDO`,name?`Cliente: ${name}`:'',...lines,notes?`Observações: ${notes}`:'','Valores e disponibilidade: confirmar com vendedor.'].filter(Boolean).join('\n')}
$('#copyQuote').onclick=async()=>{await navigator.clipboard.writeText(quoteText());toast('Lista copiada')};
$('#sendWhatsapp').onclick=()=>{const numbers=['5573999070479','5573988307382','5573991643483'];const idx=Number(localStorage.getItem('tt_seller_idx')||0)%numbers.length;localStorage.setItem('tt_seller_idx',idx+1);window.open(`https://wa.me/${numbers[idx]}?text=${encodeURIComponent(quoteText())}`,'_blank','noopener')};
$('#openQuote').onclick=()=>{$('#quoteDrawer').classList.add('open');$('#overlay').classList.add('open');$('#quoteDrawer').setAttribute('aria-hidden','false')};function closeDrawer(){$('#quoteDrawer').classList.remove('open');$('#overlay').classList.remove('open');$('#quoteDrawer').setAttribute('aria-hidden','true')}$('#closeQuote').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;

function newConversation(render=true){state.messages=[{role:'bot',text:'Olá! Sou o Assistente TEM TUDO. Posso localizar produtos, comparar opções, interpretar uma lista e montar seu orçamento. Como posso ajudar?'}];if(render)renderChat();else renderChat()}
function renderChat(){const box=$('#chatMessages');box.innerHTML=state.messages.map(m=>`<p class="bubble ${m.role==='user'?'user':'bot'}">${escapeHtml(m.text).replace(/\n/g,'<br>')}</p>`).join('');box.scrollTop=box.scrollHeight}
function sendUser(text){text=(text||'').trim();if(!text)return;state.messages.push({role:'user',text});renderChat();setTimeout(()=>{state.messages.push({role:'bot',text:answer(text)});renderChat()},220)}
function searchProducts(text,limit=5){const words=normalize(text).split(' ').filter(w=>w.length>1);return state.products.map(p=>{const hay=normalize([p.sku,p.name,p.brand,p.category,p.application,(p.tags||[]).join(' ')].join(' '));let score=0;words.forEach(w=>{if(normalize(p.sku)===w)score+=20;else if(hay.includes(w))score+=3});if(normalize(text).includes(normalize(p.sku)))score+=30;return{p,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.p)}
function answer(text){const n=normalize(text);if(/(oi|ola|bom dia|boa tarde|boa noite)/.test(n)&&n.split(' ').length<6)return'Olá! Diga qual produto, referência ou serviço você procura. Você também pode enviar uma lista ou arquivo.';if(/(orcamento|cotacao|lista)/.test(n)&&quoteEntries().length)return`Seu orçamento já possui ${quoteEntries().length} produto(s) diferente(s). Posso continuar adicionando itens ou você pode abrir a área Orçamento para revisar.`;if(/(preco|valor|estoque|disponivel)/.test(n))return'Para evitar informação incorreta, preços e disponibilidade precisam ser confirmados pelo vendedor. Posso localizar o produto e colocá-lo no orçamento agora.';if(/(garantia)/.test(n))return'A garantia varia conforme marca e produto. Preciso da referência ou modelo exato para consultar uma fonte oficial; sem isso, não vou estimar um prazo.';const results=searchProducts(text);if(results.length){const top=results.slice(0,4);return`Encontrei estas opções no catálogo:\n${top.map((p,i)=>`${i+1}. ${p.name} — ${p.brand} — Ref. ${p.sku}`).join('\n')}\n\nDiga a referência que deseja adicionar ou informe tensão, medida e aplicação para eu restringir a busca.`}state.misses++;updateMetrics();return'Não encontrei uma correspondência segura com as informações atuais. Pode enviar a marca, referência, medida, tensão, foto ou explicar qual serviço pretende realizar? Não vou indicar um produto sem confiança suficiente.'}
$('#chatForm').onsubmit=e=>{e.preventDefault();sendUser($('#chatInput').value);$('#chatInput').value=''};$('#chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit()}};$('#newChat').onclick=()=>newConversation();$$('[data-prompt]').forEach(b=>b.onclick=()=>sendUser(b.dataset.prompt));

function parseLines(text){return text.split(/\r?\n/).map(l=>l.trim()).filter(Boolean).map((line,i)=>{const qtyMatch=line.match(/^\s*(\d+(?:[.,]\d+)?)\s*(?:x|un|und|unid|pc|pcs|pç)?\s*[-–—:]?\s*/i);const qty=qtyMatch?Number(qtyMatch[1].replace(',','.')):1;const desc=line.replace(/^\s*\d+(?:[.,]\d+)?\s*(?:x|un|und|unid|pc|pcs|pç)?\s*[-–—:]?\s*/i,'').trim();const matches=searchProducts(desc,3);return{id:`r${Date.now()}${i}`,selected:true,qty,desc,sku:matches[0]?.sku||'',confidence:matches.length?Math.min(98,55+matches.length*10):20}})}
async function readFile(file){const ext=file.name.split('.').pop().toLowerCase();if(['txt','csv','json'].includes(ext))return parseLines(await file.text());if(['xlsx','xls'].includes(ext)&&window.XLSX){const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const rows=[];wb.SheetNames.forEach(name=>{const arr=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:false});arr.forEach(r=>{const line=r.filter(Boolean).join(' | ').trim();if(line)rows.push(line)})});return parseLines(rows.join('\n'))}if(ext==='pdf'){try{const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.4.168/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.4.168/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();text+=content.items.map(x=>x.str).join(' ')+'\n'}return parseLines(text)}catch{return[{id:'pdf',selected:false,qty:1,desc:`PDF recebido: ${file.name}. Não foi possível extrair texto automaticamente neste navegador.`,sku:'',confidence:0}]}}if(file.type.startsWith('image/')&&window.Tesseract){const result=await Tesseract.recognize(file,'por',{logger:m=>{$('#fileStatus').textContent=`OCR: ${Math.round((m.progress||0)*100)}%`}});return parseLines(result.data.text)}return[{id:'unknown',selected:false,qty:1,desc:`Formato não reconhecido: ${file.name}`,sku:'',confidence:0}]}
let reviewed=[];$('#fileInput').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;$('#fileStatus').textContent='Analisando arquivos...';reviewed=[];for(const file of files){try{reviewed.push(...await readFile(file))}catch(err){reviewed.push({id:`err${Date.now()}`,selected:false,qty:1,desc:`Falha ao ler ${file.name}: ${err.message}`,sku:'',confidence:0})}state.files++;save()}renderReview();$('#fileStatus').textContent=`${files.length} arquivo(s) processado(s)`;location.hash='assistente'};
function renderReview(){$('#importReview').classList.remove('hidden');$('#reviewItems').innerHTML=reviewed.map((r,i)=>`<div class="review-row"><input type="checkbox" data-rsel="${i}" ${r.selected?'checked':''}><input type="text" data-rdesc="${i}" value="${escapeHtml(r.desc)}"><input type="number" min="0.01" step="0.01" data-rqty="${i}" value="${r.qty}"><input type="text" data-rsku="${i}" placeholder="Referência" value="${escapeHtml(r.sku)}"><small>Confiança ${r.confidence}%</small></div>`).join('');updateMetrics()}
$('#closeReview').onclick=()=>$('#importReview').classList.add('hidden');$('#addReviewed').onclick=()=>{reviewed.forEach((r,i)=>{const sel=$(`[data-rsel="${i}"]`).checked;const sku=$(`[data-rsku="${i}"]`).value.trim();const qty=Number($(`[data-rqty="${i}"]`).value||1);if(sel&&findProduct(sku))addQuote(sku,qty)});toast('Itens válidos adicionados');location.hash='orcamento'};

function updateMetrics(){$('#metricProducts').textContent=state.products.length;$('#metricQuote').textContent=quoteEntries().reduce((s,x)=>s+x.qty,0);$('#metricFiles').textContent=state.files;$('#metricMisses').textContent=state.misses}
$('#importCatalog').onclick=()=>{try{const data=JSON.parse($('#catalogImport').value);if(!Array.isArray(data))throw new Error('O JSON deve ser uma lista.');let added=0;data.forEach((p,i)=>{const sku=String(p.sku??p.codigo??p.referencia??'').trim();const name=String(p.name??p.nome??p.descricao??'').trim();if(!sku||!name)return;if(state.products.some(x=>x.sku===sku))return;state.products.push({sku,name,brand:String(p.brand??p.marca??'Sem marca'),category:String(p.category??p.categoria??'Outros'),application:String(p.application??p.aplicacao??''),tags:Array.isArray(p.tags)?p.tags:[]});added++});save();renderBrands();renderCatalog();updateMetrics();$('#catalogImportStatus').textContent=`${added} produto(s) importado(s).`;}catch(err){$('#catalogImportStatus').textContent=`Erro: ${err.message}`}};
function runTests(){const tests=[['Catálogo possui itens',state.products.length>0],['SKUs são únicos',new Set(state.products.map(p=>p.sku)).size===state.products.length],['Busca encontra referência',searchProducts('4838').some(p=>p.sku==='4838')],['Busca entende aplicação',searchProducts('furar concreto').length>0],['Orçamento persiste',typeof state.quote==='object'],['Parser reconhece quantidade',parseLines('3x Furadeira de impacto')[0].qty===3],['Fallback sem invenção',answer('qual o estoque agora').includes('confirmados')],['Layout possui rotas',$$('.page').length>=5]];$('#diagnostics').innerHTML=tests.map(([name,ok])=>`<div class="diagnostic-item"><span>${escapeHtml(name)}</span><strong class="${ok?'pass':'fail'}">${ok?'APROVADO':'FALHOU'}</strong></div>`).join('');toast(`${tests.filter(x=>x[1]).length}/${tests.length} testes aprovados`)}
$('#runTests').onclick=runTests;runTests();
load();