/* TEM TUDO — experiência pública e busca inteligente v2 */
(()=>{
'use strict';
const ALIASES={
 'soq':'soquete','soc':'soquete','soq.':'soquete','chav':'chave','ch':'chave','comb':'combinada','chav comb':'chave combinada','chave comb':'chave combinada','chav ph':'chave philips','ch ph':'chave philips','ph':'philips','phillips':'philips','chav fen':'chave fenda','ch fen':'chave fenda','fen':'fenda','chav boca':'chave fixa','chave boca':'chave fixa','boca':'fixa','chav fixa':'chave fixa','ali':'alicate','alic':'alicate','uni':'universal','paraf':'parafusadeira','furad':'furadeira','esmer':'esmerilhadeira','esmerilh':'esmerilhadeira','lixad':'lixadeira','mart':'martelete','marte':'martelete','comp':'compressor','mang':'mangueira','eng':'engate','pist':'pistola','adapt':'adaptador','ext':'extensão','reg':'registro','joel':'joelho','disj':'disjuntor','tom':'tomada','lamp':'lâmpada','elet':'eletrodo','inox':'aço inox','aco':'aço','alum':'alumínio','mad':'madeira','conc':'concreto','alven':'alvenaria','ferro':'metal','p/':'para','c/':'com','s/':'sem','jg':'jogo','jog':'jogo','kit':'jogo','un':'unidade','und':'unidade','unid':'unidade','pc':'peça','pcs':'peças','pç':'peça','qtd':'quantidade','pol':'polegada','pol.':'polegada','mt':'metro','mts':'metros','cm':'centímetro','mm':'milímetro','kg':'quilo','gr':'grama','lt':'litro','l':'litro','cv':'cavalo vapor','hp':'horse power','v':'volt','bat':'bateria','maq':'máquina','maq solda':'máquina solda','sold':'solda','broc':'broca','disc':'disco','serr':'serra','rol':'rolamento','rolam':'rolamento','rolamento':'rolamento'
};
const PHRASES=Object.keys(ALIASES).filter(k=>k.includes(' ')).sort((a,b)=>b.length-a.length);
const typo=[[/esmerilh?ad[ae]r?a/g,'esmerilhadeira'],[/furad[ei]ra/g,'furadeira'],[/parafuzadeira/g,'parafusadeira'],[/phil?l?ips/g,'philips'],[/soquet[ei]/g,'soquete'],[/martelet[ei]/g,'martelete'],[/brok?a/g,'broca'],[/chav[ei]/g,'chave'],[/combinad[ao]/g,'combinada']];
const clean=s=>(s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/([0-9])\s*(?:mm|milimetros?)/g,'$1 milimetro').replace(/([0-9])\s*(?:cm|centimetros?)/g,'$1 centimetro').replace(/([0-9])\s*(?:v|volts?)/g,'$1 volt').replace(/([0-9])\s*(?:pol|polegadas?|")/g,'$1 polegada').replace(/[^a-z0-9/.,]+/g,' ').trim();
function expand(raw){let s=clean(raw);typo.forEach(([r,v])=>s=s.replace(r,v));PHRASES.forEach(k=>{const r=new RegExp('\\b'+k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','g');s=s.replace(r,ALIASES[k])});let tokens=s.split(/\s+/).filter(Boolean).map(t=>ALIASES[t]||t);tokens=tokens.flatMap(t=>t==='metal'?['metal','ferro','aco']:t==='fixa'?['fixa','boca']:t==='philips'?['philips','phillips','estrela']:t==='milimetro'?['milimetro','mm']:[t]);return [...new Set(tokens)].join(' ')}
function productText(p){return clean([p.sku,p.name,p.brand,p.category,p.application,p.reference,(p.tags||[]).join(' ')].join(' '))}
function scoreProduct(p,query){const q=expand(query);if(!q)return 1;const words=q.split(' ').filter(w=>w.length>1);const hay=productText(p);const sku=clean(p.sku);const ref=clean(p.reference);let score=0,matched=0;for(const w of words){if(w===sku||w===ref){score+=60;matched++;continue}if(sku.includes(w)||ref.includes(w)){score+=25;matched++;continue}if(hay.includes(w)){score+=8;matched++;continue}if(w.length>4&&hay.split(' ').some(x=>x.startsWith(w.slice(0,-1)))){score+=3;matched++}}
 const ratio=matched/Math.max(words.length,1);if(ratio<.45)return 0;if(ratio===1)score+=20;return score}
let view=localStorage.getItem('tt_view')||'grid',page=1;const PAGE_SIZE=30;
const icon=p=>{const t=clean(p.category+' '+p.name);if(/broca|furadeira|martelete/.test(t))return'🛠️';if(/chave|soquete|alicate/.test(t))return'🔧';if(/disco|serra|corte/.test(t))return'⚙️';if(/bomba|agua|hidraul/.test(t))return'💧';if(/solda|eletrodo/.test(t))return'⚡';if(/motor|compressor/.test(t))return'🔩';return'🧰'};
function installToolbar(){const stats=document.querySelector('#catalogStats');if(!stats||document.querySelector('.catalog-toolbar'))return;const bar=document.createElement('div');bar.className='catalog-toolbar';bar.innerHTML='<div class="customer-only-note">Digite como você costuma pedir: <b>“2 brocas 8 mm ferro”</b>, <b>“soq 17 impacto”</b> ou uma referência.</div><div class="view-switch" aria-label="Modo de visualização"><button data-view="grid">▦ Grade</button><button data-view="list">☷ Lista</button></div>';stats.parentNode.insertBefore(bar,stats);bar.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;localStorage.setItem('tt_view',view);page=1;renderCatalog()})}
function installMobileNav(){if(document.querySelector('.mobile-bottom-nav'))return;document.body.insertAdjacentHTML('beforeend','<nav class="mobile-bottom-nav" aria-label="Navegação rápida"><a href="#catalogo"><b>⌕</b>Produtos</a><a href="#assistente"><b>💬</b>Assistente</a><a href="#orcamento"><b>🧾</b>Orçamento</a><a href="https://wa.me/5573999070479" target="_blank" rel="noopener"><b>◉</b>WhatsApp</a></nav>')}
function removeTechnicalArea(){document.querySelector('#mainNav a[href="#admin"]')?.remove();document.querySelector('#admin')?.remove();if(location.hash==='#admin')location.hash='catalogo';window.addEventListener('hashchange',()=>{if(location.hash==='#admin')location.hash='catalogo'})}
window.filtered=function(){const q=state.search;return state.products.map(p=>({p,score:scoreProduct(p,q)})).filter(x=>(state.brand==='Todas'||x.p.brand===state.brand)&&(!q||x.score>0)).sort((a,b)=>b.score-a.score||a.p.name.localeCompare(b.p.name)).map(x=>x.p)};
window.productCard=function(p){const tags=[p.category,p.reference,...(p.tags||[])].filter(Boolean).slice(0,3);return `<article class="product-card"><div class="product-visual" aria-hidden="true">${icon(p)}</div><div class="product-body"><div class="product-meta"><span>${escapeHtml(p.brand||'TEM TUDO')}</span><span>•</span><span>Cód. ${escapeHtml(p.sku)}</span></div><h3>${escapeHtml(p.name)}</h3>${p.reference?`<div class="product-ref">Referência: <strong>${escapeHtml(p.reference)}</strong></div>`:''}<div class="product-tags">${tags.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><div class="availability-note">Disponibilidade sob consulta</div></div><footer><button class="btn secondary" data-ask="${escapeHtml(p.sku)}">Detalhes</button><button class="btn primary" data-add="${escapeHtml(p.sku)}">Adicionar</button></footer></article>`};
window.renderCatalog=function(){installToolbar();const all=filtered();const pages=Math.max(1,Math.ceil(all.length/PAGE_SIZE));if(page>pages)page=pages;const start=(page-1)*PAGE_SIZE,items=all.slice(start,start+PAGE_SIZE);document.querySelector('#catalogStats').textContent=state.search?`${all.length} resultado(s) encontrado(s)`:`${state.products.length} produtos no catálogo`;const grid=document.querySelector('#productGrid');grid.classList.toggle('list-view',view==='list');grid.innerHTML=items.length?items.map(productCard).join(''):'<div class="empty-state">Não encontrei uma correspondência segura. Tente informar medida, aplicação, marca ou referência.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addQuote(b.dataset.add));document.querySelectorAll('[data-ask]').forEach(b=>b.onclick=()=>{const p=findProduct(b.dataset.ask);location.hash='assistente';setTimeout(()=>sendUser(`Quero saber mais sobre ${p.name} (${p.sku})`),100)});let pager=document.querySelector('#catalogPagination');if(!pager){pager=document.createElement('div');pager.id='catalogPagination';pager.className='pagination';grid.after(pager)}const nums=[];for(let n=Math.max(1,page-2);n<=Math.min(pages,page+2);n++)nums.push(n);pager.innerHTML=`<button data-page="${page-1}" ${page===1?'disabled':''}>‹</button>${nums.map(n=>`<button data-page="${n}" class="${n===page?'active':''}">${n}</button>`).join('')}<button data-page="${page+1}" ${page===pages?'disabled':''}>›</button>`;pager.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=Math.min(pages,Math.max(1,Number(b.dataset.page)));renderCatalog();document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view))};
window.searchProducts=function(text,limit=5){return state.products.map(p=>({p,score:scoreProduct(p,text)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.p)};
window.answer=function(text){const n=expand(text);if(/^(oi|ola|bom dia|boa tarde|boa noite)/.test(n)&&n.split(' ').length<7)return'Olá! Diga o produto, medida, referência ou o serviço que pretende fazer. Você pode escrever de forma abreviada, por exemplo: “2 soq 17 impacto”.';if(/preco|valor|estoque|disponivel/.test(n))return'Posso localizar e montar a lista, mas preço e disponibilidade serão confirmados pelo vendedor para evitar informação incorreta.';if(/garantia/.test(n))return'A garantia depende da marca e da referência exata. Informe o modelo ou código para uma consulta segura.';const qty=(clean(text).match(/^\s*(\d+(?:[.,]\d+)?)/)||[])[1];const results=searchProducts(text,5);if(results.length){const top=results[0],others=results.slice(1,4);return `${qty?`Entendi a quantidade: ${qty}.\n\n`:''}Melhor correspondência encontrada:\n${top.name}\nMarca: ${top.brand} · Código: ${top.sku}${top.reference?` · Referência: ${top.reference}`:''}\n\n${others.length?`Outras opções:\n${others.map((p,i)=>`${i+1}. ${p.name} — ${p.brand} — Cód. ${p.sku}`).join('\n')}\n\n`:''}Informe o código que deseja adicionar ou diga uma característica para refinar, como medida, tensão, material ou tipo de uso.`}state.misses++;updateMetrics();return'Não encontrei uma correspondência segura. Informe, quando possível: tipo do produto, medida, aplicação, marca ou referência. Também aceito abreviações e foto/lista.'};
function boot(){removeTechnicalArea();installMobileNav();installToolbar();page=1;renderCatalog();const input=document.querySelector('#catalogSearch');if(input)input.addEventListener('input',()=>{page=1},{capture:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();
